// Mock initial data for English Vault
export const initialRecords = [
  {
    __backendId: 'm1', type: 'Vocabulary', word: 'Serendipity',
    meaning: 'The occurrence of finding pleasant things by chance.',
    spanish: 'Serendipia / casualidad afortunada',
    example: 'Meeting my best friend was pure serendipity.',
    my_example: 'It was serendipity that we sat next to each other on the plane.',
    register: 'Neutral', level: 'C1', variety: 'Both',
    topic: 'Feelings', tags: 'lucky, chance, positive',
    is_favourite: true, is_difficult: false, is_known: false, needs_review: true,
    status: 'Learning', synonyms: 'chance, fluke, fortune',
    related: 'happy accident, stroke of luck',
    review_count: 3, review_score: 2,
    created_at: '2025-06-10T10:00:00Z',
  },
  {
    __backendId: 'm2', type: 'Slang', word: 'Ghost (someone)',
    meaning: 'To suddenly stop all communication with someone without explanation.',
    spanish: 'Hacer ghosting / desaparecer',
    example: "I can't believe he ghosted me after three dates.",
    my_example: 'She ghosted the whole group chat.',
    register: 'Informal', level: 'B2', variety: 'Both',
    topic: 'Relationships', tags: 'dating, modern, social media',
    is_favourite: false, is_difficult: false, is_known: false, needs_review: true,
    status: 'New', how_common: 'Very common among young adults',
    offensive_warning: 'Casual usage, not offensive',
    slang_tags: 'internet, dating',
    review_count: 0, review_score: 0,
    created_at: '2025-06-15T09:00:00Z',
  },
  {
    __backendId: 'm3', type: 'Phrasal Verb', word: 'Come across',
    meaning: 'To find or meet by chance; to appear or seem a certain way.',
    spanish: 'Encontrarse con / parecer',
    example: 'I came across an old photo of us yesterday.',
    my_example: 'She comes across as very confident.',
    register: 'Neutral', level: 'B1', variety: 'Both',
    topic: 'Everyday', tags: 'discovery, appearance',
    is_favourite: true, is_difficult: false, is_known: false, needs_review: true,
    status: 'Almost learnt', separable: 'Inseparable',
    transitive: 'Both (transitive with object)',
    similar_expressions: 'run into, bump into, stumble upon',
    review_count: 5, review_score: 4,
    created_at: '2025-06-20T14:30:00Z',
  },
  {
    __backendId: 'm4', type: 'Expression', word: 'Piece of cake',
    meaning: 'Something very easy to do.',
    spanish: 'Pan comido / muy fácil',
    example: "The exam was a piece of cake!",
    my_example: 'For her, cooking is a piece of cake.',
    register: 'Informal', level: 'B1', variety: 'Both',
    topic: 'Difficulty', tags: 'easy, idiom, food',
    is_favourite: false, is_difficult: false, is_known: true, needs_review: false,
    status: 'Mastered', synonyms: 'a breeze, child\'s play',
    review_count: 8, review_score: 6,
    created_at: '2025-06-01T08:00:00Z',
  },
  {
    __backendId: 'm5', type: 'Collocation', word: 'Make a decision',
    meaning: 'To decide on something; to choose a course of action.',
    spanish: 'Tomar una decisión',
    example: 'You need to make a decision by Friday.',
    my_example: "I made the decision to move abroad.",
    register: 'Neutral', level: 'A2', variety: 'Both',
    topic: 'Business', tags: 'common, verb+noun',
    is_favourite: false, is_difficult: false, is_known: false, needs_review: true,
    status: 'Learning',
    related: 'reach a decision, come to a decision',
    review_count: 2, review_score: 1,
    created_at: '2025-06-22T11:00:00Z',
  },
  {
    __backendId: 'm6', type: 'Idiom', word: 'Break the ice',
    meaning: 'To do or say something to relieve tension or start a conversation in a formal situation.',
    spanish: 'Romper el hielo',
    example: 'He told a joke to break the ice at the meeting.',
    my_example: "Let's play a game to break the ice.",
    register: 'Neutral', level: 'B2', variety: 'Both',
    topic: 'Social', tags: 'conversation, social, idiom',
    is_favourite: true, is_difficult: false, is_known: false, needs_review: true,
    status: 'Almost learnt',
    review_count: 4, review_score: 3,
    created_at: '2025-06-25T16:00:00Z',
  },
  {
    __backendId: 'm7', type: 'Connector / Linker', word: 'Nevertheless',
    meaning: 'In spite of that; however; despite what has just been said.',
    spanish: 'Sin embargo / no obstante',
    example: 'The weather was cold; nevertheless, we enjoyed the picnic.',
    my_example: "It's difficult; nevertheless, I'll try my best.",
    register: 'Formal', level: 'B2', variety: 'Both',
    topic: 'Writing', tags: 'contrast, formal, discourse',
    is_favourite: false, is_difficult: true, is_known: false, needs_review: true,
    status: 'Learning', synonyms: 'however, nonetheless, still',
    review_count: 1, review_score: 0,
    created_at: '2025-07-01T12:00:00Z',
  },
  {
    __backendId: 'm8', type: 'Grammar / Trick', word: 'Present Perfect vs Past Simple',
    meaning: '',
    separable: 'Tenses',
    transitive: 'Use Present Perfect for actions connected to now. Use Past Simple for completed actions at a specific past time.',
    how_common: 'Present Perfect emphasises the result or connection to the present. Past Simple focuses on when it happened.',
    synonyms: 'I have lived here for 5 years. (still living)\nI lived there for 5 years. (finished)\nHave you ever been to Paris?\nI went to Paris last summer.',
    offensive_warning: 'With specific time markers (yesterday, in 1999, last week), always use Past Simple.',
    related: 'Think: "Present Perfect = still relevant", "Past Simple = closed chapter".',
    notes: 'Common mistake: "I have seen him yesterday" ❌ → "I saw him yesterday" ✓',
    level: 'B1', variety: 'Both',
    topic: 'Grammar', tags: 'tenses, verbs, essential',
    is_favourite: true, is_difficult: true, is_known: false, needs_review: true,
    status: 'Learning',
    review_count: 6, review_score: 3,
    created_at: '2025-06-28T09:30:00Z',
  },
  {
    __backendId: 'm9', type: 'Vocabulary', word: 'Eloquent',
    meaning: 'Fluent or persuasive in speaking or writing.',
    spanish: 'Elocuente',
    example: 'She gave an eloquent speech at the ceremony.',
    my_example: 'His eloquent argument convinced the jury.',
    register: 'Formal', level: 'C1', variety: 'Both',
    topic: 'Communication', tags: 'speaking, formal, positive',
    is_favourite: false, is_difficult: false, is_known: false, needs_review: true,
    status: 'New', synonyms: 'articulate, expressive, fluent',
    review_count: 0, review_score: 0,
    created_at: '2025-07-02T15:00:00Z',
  },
  {
    __backendId: 'm10', type: 'Phrasal Verb', word: 'Look up to',
    meaning: 'To admire or respect someone.',
    spanish: 'Admirar / respetar',
    example: 'I really look up to my older sister.',
    my_example: 'Many young players look up to him.',
    register: 'Neutral', level: 'B1', variety: 'Both',
    topic: 'Relationships', tags: 'admiration, respect',
    is_favourite: false, is_difficult: false, is_known: false, needs_review: true,
    status: 'Learning', separable: 'Inseparable',
    transitive: 'Transitive', similar_expressions: 'admire, respect, idolize',
    review_count: 2, review_score: 1,
    created_at: '2025-07-03T10:00:00Z',
  },
  {
    __backendId: 'm11', type: 'Slang', word: 'Lit',
    meaning: 'Exciting, excellent, or amazing.',
    spanish: 'Genial / increíble',
    example: 'That party last night was lit!',
    my_example: "The concert was so lit.",
    register: 'Slang', level: 'B2', variety: 'American English',
    topic: 'Entertainment', tags: 'party, positive, gen-z',
    is_favourite: false, is_difficult: false, is_known: true, needs_review: false,
    status: 'Mastered', how_common: 'Very common in casual speech',
    slang_tags: 'gen-z, party',
    review_count: 5, review_score: 5,
    created_at: '2025-06-18T20:00:00Z',
  },
  {
    __backendId: 'm12', type: 'Connector / Linker', word: 'Furthermore',
    meaning: 'In addition; besides. Used to introduce additional supporting information.',
    spanish: 'Además / asimismo',
    example: 'The project is over budget. Furthermore, it is behind schedule.',
    my_example: 'The food was great. Furthermore, the service was excellent.',
    register: 'Formal', level: 'B2', variety: 'Both',
    topic: 'Writing', tags: 'addition, formal, discourse',
    is_favourite: false, is_difficult: false, is_known: false, needs_review: true,
    status: 'Almost learnt', synonyms: 'moreover, additionally, besides',
    review_count: 3, review_score: 2,
    created_at: '2025-07-04T11:00:00Z',
  },
];
